name: orbitnetmobileapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  syncfusion_flutter_datepicker: ^25.1.41
  google_fonts: ^4.0.4
  toggle_switch: ^2.3.0
  flutter_screenutil: ^5.0.0+2
  flutter_spinkit: ^5.0.0
  after_layout: ^1.1.0
  connectivity_plus: ^5.0.1
  permission_handler: ^11.0.1
  animated_splash_screen: ^1.1.0
  intl: ^0.18.1
  flutter_date_range_picker: ^0.0.14
  simple_animations: ^4.1.0
  supercharged: ^2.1.1
  shared_preferences: ^2.2.2

# ⚠️ OVERRIDES CORRIGÉS :
dependency_overrides:
  win32: ^5.0.0  # ← Version simple au lieu de git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/icon.png